libs/com.etendorx.generate_entities/build.gradle, modules_core/com.etendorx.das/build.gradle, rxconfig/das.yaml.template, settings.gradle
New guide and changes on default config
=> Feature EPL-361: Database connection

libs/com.etendorx.generate_entities.core/build.gradle, libs/com.etendorx.generate_entities/build.gradle, libs/com.etendorx.generate_entities/src/main/java/com/etendorx/gen/GenerateEntitiesApplication.java
Adding condition to prevent generating files when a projection does not have entities
=> Feature EPL-376: Filter projections

libs/com.etendorx.clientrest_core/build.gradle, libs/com.etendorx.das_core/build.gradle, libs/com.etendorx.generate_entities.core/build.gradle, libs/com.etendorx.generate_entities.extradomaintype/build.gradle, libs/com.etendorx.generate_entities/build.gradle, modules_core/com.etendorx.asyncprocess/build.gradle, modules_core/com.etendorx.auth/build.gradle, modules_core/com.etendorx.configserver/build.gradle, modules_core/com.etendorx.das/build.gradle, modules_core/com.etendorx.edge/build.gradle, pipelines/publish-snapshots/Jenkinsfile, settings.gradle
Feature ETO-71: Add versionJars variable in settings.gradle
=> Feature ETO-71: Add jenkinsfile for snapshot jars publication

libs/com.etendorx.generate_entities/src/main/java/com/etendorx/gen/util/MetadataUtil.java, modules_core/com.etendorx.das/src/test/java/com/etendorx/das/test/RestCallTest.java, modules_test/com.etendorx.test.grpc/src-db/das/metadata.json
Adding projection field values verification
=> Feature EPL-373: Adding field verification

pipelines/publish-snapshots/Jenkinsfile, pipelines/run-tests/Jenkinsfile
Add step in which the rx module is cloned in core
=> Feature ETO-78: Refactor Jenkinsfile

libs/com.etendorx.generate_entities/src/main/resources/org/openbravo/base/react/modelservice.ts.ftl
=> Issue #35: Delete hardcoded entity field in modelservice.ts.flt

libs/com.etendorx.generate_entities/src/main/resources/org/openbravo/base/react/model.types.ftl
=> Issue #35: Fix generation of search type parameters

build.gradle, libs/com.etendorx.clientrest_core/build.gradle, libs/com.etendorx.das_core/build.gradle, libs/com.etendorx.generate_entities.core/build.gradle, libs/com.etendorx.generate_entities.extradomaintype/build.gradle, libs/com.etendorx.generate_entities/build.gradle, modules_core/com.etendorx.asyncprocess/build.gradle, modules_core/com.etendorx.auth/build.gradle, modules_core/com.etendorx.configserver/build.gradle, modules_core/com.etendorx.das/build.gradle, modules_core/com.etendorx.edge/build.gradle, pipelines/publish-snapshots/Jenkinsfile, settings.gradle
Rename external variable 'gradle.ext.version' in settings.gradle
=> Feature EPL-616: Add 'upgradeRxVersion' gradle task

libs/com.etendorx.utils.auth/src/main/java/com/etendorx/utils/auth/key/context/FilterContext.java, libs/com.etendorx.utils.auth/src/main/java/com/etendorx/utils/auth/key/context/UserContext.java, modules_core/com.etendorx.das/src/main/java/com/etendorx/das/hibernate_interceptor/CustomInterceptor.java, modules_core/com.etendorx.das/src/main/java/com/etendorx/das/utils/DefaultFilters.java, modules_core/com.etendorx.das/src/test/java/com/etendorx/das/utils/DefaultFiltersTest.java
=> Issue #48: Workaround to fix critical error

gradle.properties.template, pipelines/publish-snapshots/Jenkinsfile, pipelines/run-tests/Jenkinsfile, settings.gradle
Add Github credentials in environment of Snapshots Jenkinsfile
=> Feature EPL-798: Add Github repository in settings.gradle

libs/com.etendorx.das_core/src/main/java/com/etendorx/entities/mapper/lib/BindedRestController.java, libs/com.etendorx.das_core/src/main/java/com/etendorx/entities/mapper/lib/JsonPathConverter.java, libs/com.etendorx.das_core/src/main/java/com/etendorx/entities/mapper/lib/JsonPathConverterBase.java, libs/com.etendorx.das_core/src/main/java/com/etendorx/entities/mapper/lib/JsonPathEntityRetriever.java, libs/com.etendorx.das_core/src/main/java/com/etendorx/entities/mapper/lib/JsonPathEntityRetrieverBase.java, libs/com.etendorx.generate_entities.core/build.gradle, libs/com.etendorx.generate_entities.core/src/main/java/com/etendoerp/etendorx/model/projection/ETRXEntityField.java, libs/com.etendorx.generate_entities.core/src/main/java/org/openbravo/base/model/ModelProvider.java, libs/com.etendorx.generate_entities/src/main/java/com/etendorx/gen/generation/GenerateEntities.java, libs/com.etendorx.generate_entities/src/main/java/com/etendorx/gen/generation/GeneratePaths.java, libs/com.etendorx.generate_entities/src/main/java/com/etendorx/gen/generation/Templates.java, libs/com.etendorx.generate_entities/src/main/java/com/etendorx/gen/generation/mapping/GenerateBaseJsonPathConverter.java, libs/com.etendorx.generate_entities/src/main/java/com/etendorx/gen/generation/mapping/GenerateBaseJsonPathRetriever.java, libs/com.etendorx.generate_entities/src/main/java/com/etendorx/gen/generation/mapping/MappingGenerationBase.java, libs/com.etendorx.generate_entities/src/main/resources/com/etendoerp/etendorx/model/projection/ETRXEntityField.hbm.xml, libs/com.etendorx.generate_entities/src/main/resources/org/openbravo/base/gen/baseDASRepository.ftl, libs/com.etendorx.generate_entities/src/main/resources/org/openbravo/base/gen/baseDTORepository.ftl, libs/com.etendorx.generate_entities/src/main/resources/org/openbravo/base/gen/mappings/auditServiceInterceptor.ftl, libs/com.etendorx.generate_entities/src/main/resources/org/openbravo/base/gen/mappings/baseDTO.ftl, libs/com.etendorx.generate_entities/src/main/resources/org/openbravo/base/gen/mappings/baseFieldConverterWrite.ftl, libs/com.etendorx.generate_entities/src/main/resources/org/openbravo/base/gen/mappings/baseJsonPathConverter.ftl, libs/com.etendorx.generate_entities/src/main/resources/org/openbravo/base/gen/mappings/baseJsonPathRetriever.ftl, libs/com.etendorx.generate_entities/src/main/resources/org/openbravo/base/gen/mappings/baseRepository.ftl, libs/com.etendorx.generate_entities/src/main/resources/org/openbravo/base/gen/mappings/baseRestController.ftl, libs/com.etendorx.utils.auth/src/main/java/com/etendorx/utils/auth/key/context/FilterContext.java, modules_core/com.etendorx.das/src/main/java/com/etendorx/das/hibernate_interceptor/AuditServiceInterceptorImpl.java
Spring Boot REST Controller for JSON Path-based Data Mapping
=> Feature EPL-877: Refactor DTO Converters in DAS with jsonPath

libs/com.etendorx.generate_entities/src/main/resources/org/openbravo/base/gen/mappings/baseFieldConverterWrite.ftl, libs/com.etendorx.generate_entities/src/main/resources/org/openbravo/base/gen/mappings/baseJsonPathConverter.ftl, libs/com.etendorx.generate_entities/src/main/resources/org/openbravo/base/gen/mappings/baseJsonPathRetriever.ftl
by the dictionary definition
Add debug messages in convertion
=> Feature EPL-897: Identity fields are not generated

modules_core/com.etendorx.auth/src/main/java/com/etendorx/auth/auth/CustomAuthenticationFailureHandler.java, pipelines/run-tests/Jenkinsfile, rxconfig/auth.yaml.template
=> Feature EPL-1417: Add placeholder to start oAuth & error codes handler

.github/workflows/image-build.yml, resources/dynamic-das/Dockerfile, resources/dynamic-gradle/Dockerfile
In this pull request a new github acition pipeline is added, it executes make commands defined in the repository to be able to create a docker image, also a docker manifest is created and pushea to be able to work with multi-architectures
=> Feature ERP-774:  Dynamic-gradle and dynamic-das images build automation

libs/com.etendorx.generate_entities/src/main/resources/org/openbravo/base/gen/mappings/baseFieldConverterWrite.ftl
=> Feature ETP-438: Fix renaming list in mapping generation.

libs/com.etendorx.das_core/src/main/java/com/etendorx/entities/metadata/FieldMetadata.java, libs/com.etendorx.generate_entities/src/main/resources/org/openbravo/base/gen/entityMetadata.ftl, libs/com.etendorx.utils.common/build.gradle, libs/com.etendorx.utils.common/src/main/java/com/etendorx/utils/common/PathManagementUtils.java, modules_core/com.etendorx.das/src/main/java/com/etendorx/das/connector/OBCONFieldMapping.java
=> Feature ETP-404: Added Path Management utils and property calculation.

libs/com.etendorx.utils.common/build.gradle
=> Feature ETP-404: Added PathUtils lib to publish configuration.

libs/com.etendorx.generate_entities/src/main/resources/org/openbravo/base/gen/mappings/baseDTORequest.ftl
=> Feature ETP-645: Fix generation code in DTO read request template.

libs/com.etendorx.generate_entities/src/main/resources/org/openbravo/base/gen/entityMetadata.ftl, modules_core/com.etendorx.das/src/main/java/com/etendorx/das/connector/OBCONFieldMapping.java, pipelines/run-tests/Jenkinsfile
=> Feature ETP-645: Fix generation code for entity metadata.

libs/com.etendorx.das_core/src/main/java/com/etendorx/entities/mapper/lib/DTOConverter.java, libs/com.etendorx.das_core/src/main/java/com/etendorx/entities/mapper/lib/DefaultValuesHandler.java, libs/com.etendorx.das_core/src/main/java/com/etendorx/entities/mapper/lib/PostSyncService.java, libs/com.etendorx.generate_entities/src/main/java/com/etendorx/gen/generation/mapping/GenerateBaseDTOConverter.java, libs/com.etendorx.generate_entities/src/main/resources/org/openbravo/base/gen/baseDTORepository.ftl, libs/com.etendorx.generate_entities/src/main/resources/org/openbravo/base/gen/mappings/auditServiceInterceptor.ftl, libs/com.etendorx.generate_entities/src/main/resources/org/openbravo/base/gen/mappings/baseDTOConverter.ftl, libs/com.etendorx.generate_entities/src/main/resources/org/openbravo/base/gen/mappings/baseFieldConverterWrite.ftl, libs/com.etendorx.generate_entities/src/main/resources/org/openbravo/base/gen/mappings/baseRepository.ftl, libs/com.etendorx.utils.common/src/main/java/com/etendorx/utils/common/PathManagementUtils.java, modules_core/com.etendorx.das/src/main/java/com/etendorx/das/connector/OBCONFieldMapping.java, modules_core/com.etendorx.das/src/main/java/com/etendorx/das/externalid/ExternalIdServiceImpl.java, modules_core/com.etendorx.das/src/main/java/com/etendorx/das/externalid/PostSyncServiceImpl.java, modules_core/com.etendorx.das/src/main/java/com/etendorx/das/hibernate_interceptor/AuditServiceInterceptorImpl.java, modules_core/com.etendorx.das/src/main/java/com/etendorx/das/utils/DefaultFilters.java, modules_core/com.etendorx.das/src/test/java/com/etendorx/das/test/DefaultFiltersTest.java, modules_core/com.etendorx.das/src/test/java/com/etendorx/das/unit/BaseDTORepositoryDefaultTests.java
=> Feature ETP-740: Fixed ftl, subentity IDs replacement and DAS filters.

libs/com.etendorx.das_core/src/main/java/com/etendorx/entities/mapper/lib/JsonPathConverterBase.java, libs/com.etendorx.generate_entities/src/main/resources/org/openbravo/base/gen/mappings/baseFieldConverterWrite.ftl, modules_core/com.etendorx.das/build.gradle, modules_core/com.etendorx.das/src/main/java/com/etendorx/das/externalid/ExternalIdServiceImpl.java, modules_core/com.etendorx.das/src/main/java/com/etendorx/das/utils/DefaultFilters.java, modules_core/com.etendorx.das/src/test/java/com/etendorx/das/test/DefaultFiltersTest.java
=> Feature ETP-740: Changed regex to use a new SQL library.

pipelines/publish-snapshots/Jenkinsfile, pipelines/run-tests/Jenkinsfile
In this Pr the namespaces of the dynamic pods are set to match the new Jenkins server
=> Feature ETP-1547: Edit Namespaces

libs/com.etendorx.generate_entities/src/main/resources/org/openbravo/base/gen/mappings/baseFieldConverterRead.ftl, modules_core/com.etendorx.das/src/main/java/com/etendorx/das/utils/DefaultFilters.java, modules_core/com.etendorx.das/src/test/java/com/etendorx/das/test/DefaultFiltersTest.java
This pull request introduces error handling improvements and conditional logic updates to enhance the robustness of entity handling and SQL query filtering. Key changes include adding exception handling for missing entities, importing the necessary exception class, and refining SQL filter application logic.
* [`libs/com.etendorx.generate_entities/src/main/resources/org/openbravo/base/gen/mappings/baseFieldConverterRead.ftl`](diffhunk://#diff-c617611fcf1da36de549e34b6d48500bbc4f7dd22855c529a70e20f1ca9513b7L39-R39): Wrapped `mappingUtils.handleBaseObject` in a `try-catch` block to handle `EntityNotFoundException`, returning `null` if the exception is thrown.
* [`libs/com.etendorx.generate_entities/src/main/resources/org/openbravo/base/gen/mappings/baseFieldConverterRead.ftl`](diffhunk://#dif …
=> Issue #204: Fixed default filters in DAS service and clases generation

.github/workflows/image-build.yml, resources/dynamic-das/Dockerfile, resources/dynamic-das/Makefile, resources/dynamic-das/run.sh, resources/dynamic-gradle/Dockerfile, resources/dynamic-gradle/Makefile, resources/dynamic-gradle/run.sh
This pull request introduces several updates to the `dynamic-das` and `dynamic-gradle` resources, including environment upgrades, dependency changes, and the addition of new scripts to simplify the build and runtime processes. The most notable changes include upgrading the base image and Gradle version, adding support for OpenTelemetry instrumentation, and refactoring the `CMD` instructions in Dockerfiles to use external scripts for better maintainability.
* Updated base image from `mcr.microsoft.com/openjdk/jdk:17-ubuntu` to `amazoncorretto:17.0.14` in both `dynamic-das` and `dynamic-gradle` Dockerfiles. [[1]](diffhunk://#diff-4baca40679aac7b5ab30579aefd04b126d7d1e2973c234c4c4431c3a24fa52caL1-R13) [[2]](diffhunk://#diff-5c5f48ff0eda8f020832b80eafe808be0170e1382711664dfeaf8d4cabfb417eL1-R1 …
=> Feature ETP-1771: Upgrade dynamic-das and dynamic-gradle images.
